### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by FrostMegaByte** [pythonJaRvis/pythonJaRvis.github.io#1]
- I'd like to see a `README.md` file attached to this repository which also contains an example of the usage of this tool.

Why? Well I'm trying to get this tool to work and I'm running the command `python main.py --package "D:/Documents/Code Projects/test"` And I get an error: `TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType`

**Comment by Mryanhehe** [comment]
I run it in my macM1, `python3 main.py main.py --package ./`. It can succeed.

**Comment by FrostMegaByte** [comment]
Thanks! This worked and made it much clearer! I'll likely create a README to help others

**Comment by FrostMegaByte** [comment]
Opened a PR #7 which adds a README
