### ISSUE TITLE
Which file to run to run the tests in the micro-benchmark?

### ISSUE THREAD

**Issue by FrostMegaByte** [pythonJaRvis/pythonJaRvis.github.io#4]
So I'm wondering which file to run to run the tests in the micro-benchmark?
- I tried `test.sh`, but that fails on me because my specified path contains spaces.
- I tried `results.py` but that fails, because `os.walk` on Windows leads to the variable `fs` to be empty.
- I tried `base.py`, but that doesn't seem to be the file that I must run.

So I'm confused...

**Comment by FrostMegaByte** [comment]
Figured it out!

**Run all tests:**  
`python -m unittest discover -p "*_test.py"`

**Run single test:**  
`python -m unittest args_test.py`

**Comment by pythonJaRvis** [comment]
Hello, this repo is the code of my paper, just for display, so I don't visit it usually. But I Will open-source it in my own repo , if you want, you can pull requests from real repo.

**Comment by pythonJaRvis** [comment]
The repo is [https://github.com/Mryanhehe/Jarvis.git](url)
